name: pycolorbar
channels:
  - conda-forge
dependencies:
  - pyyaml
  - numpy
  - matplotlib
  - pydantic>=2.0.0
  # Docs
  - jupyter
  - sphinx
  - sphinx-book-theme
  - nbsphinx
  # Testing
  - setuptools
  - pre-commit
  - coverage
  - pytest
  - pytest-cov
  - pytest-mock
  - requests-mock
  - pip
